// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 웹 환경
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    authDomain: 'chikabooks3rd.firebaseapp.com',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    messagingSenderId: '215876124758',
    appId: '1:215876124758:web:cf277512da9f5b842bee19',
    measurementId: 'G-GYVF2JVZ1H',
  );

  // Android 환경
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    messagingSenderId: '215876124758',
    appId: '1:215876124758:android:b6d89b37d421f22b723bf7',
  );

  // iOS 환경
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    messagingSenderId: '215876124758',
    appId: '1:215876124758:ios:1623d705fd4073912bee19',
    iosClientId:
        '215876124758-aise0ql6la51arel1m0ou6csb80bsrda.apps.googleusercontent.com',
    iosBundleId: 'com.chikabooks.appnew',
  );

  // macOS 환경 (iOS와 동일)
  static const FirebaseOptions macos = ios;

  // Windows 환경 (web과 동일 App-ID만 다름)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    messagingSenderId: '215876124758',
    appId: '1:215876124758:web:cf277512da9f5b842bee19',
    measurementId: 'G-GYVF2JVZ1H',
  );
}
