// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW9j-dsh6dFSWh9NWzJ7OPRPYasvgO0E0',
    appId: '1:1022322314972:web:1de7a492567244842bee19',
    messagingSenderId: '1022322314972',
    projectId: 'chikabooks-app',
    authDomain: 'chikabooks-app.firebaseapp.com',
    storageBucket: 'chikabooks-app.firebasestorage.app',
    measurementId: 'G-WNLEHLVTB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57iT3qghJek-CrNoPKoWKybuTTsPixkk',
    appId: '1:1022322314972:android:699c2c36ebbc30462bee19',
    messagingSenderId: '1022322314972',
    projectId: 'chikabooks-app',
    storageBucket: 'chikabooks-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW9j-dsh6dFSWh9NWzJ7OPRPYasvgO0E0',
    appId: '1:1022322314972:web:cf277512da9f5b842bee19',
    messagingSenderId: '1022322314972',
    projectId: 'chikabooks-app',
    authDomain: 'chikabooks-app.firebaseapp.com',
    storageBucket: 'chikabooks-app.firebasestorage.app',
    measurementId: 'G-GYVF2JVZ1H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgB-gSurY2JKxumN1bsAV6t5bcVrscA4',
    appId: '1:1022322314972:ios:1623d705fd4073912bee19',
    messagingSenderId: '1022322314972',
    projectId: 'chikabooks-app',
    storageBucket: 'chikabooks-app.firebasestorage.app',
    iosClientId: '1022322314972-aise0ql6la51arel1m0ou6csb80bsrda.apps.googleusercontent.com',
    iosBundleId: 'com.example.chikabooksApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgB-gSurY2JKxumN1bsAV6t5bcVrscA4',
    appId: '1:1022322314972:ios:1623d705fd4073912bee19',
    messagingSenderId: '1022322314972',
    projectId: 'chikabooks-app',
    storageBucket: 'chikabooks-app.firebasestorage.app',
    iosClientId: '1022322314972-aise0ql6la51arel1m0ou6csb80bsrda.apps.googleusercontent.com',
    iosBundleId: 'com.example.chikabooksApp',
  );

}