// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    appId: '1:215876124758:web:1de7a492567244842bee19',
    messagingSenderId: '215876124758',
    projectId: 'chikabooks3rd',
    authDomain: 'chikabooks3rd.firebaseapp.com',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    measurementId: 'G-WNLEHLVTB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    appId: '1:215876124758:android:348adb3bac7ac6c7723bf7',
    messagingSenderId: '215876124758',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSsIsl1dtspv1l7r8v6zNHo28TfGwZwM',
    appId: '1:215876124758:web:cf277512da9f5b842bee19',
    messagingSenderId: '215876124758',
    projectId: 'chikabooks3rd',
    authDomain: 'chikabooks3rd.firebaseapp.com',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    measurementId: 'G-GYVF2JVZ1H',
  );

  /// iOS `GoogleService-Info.plist` 및 Firebase 콘솔 iOS 앱 `com.chikabooks.chikabooksApp`와 동일해야 함.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGKfy06xT2j01LoDGIZGKUuWi5M4slNA',
    appId: '1:215876124758:ios:f612d3d0ec4b4793723bf7',
    messagingSenderId: '215876124758',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    iosClientId:
        '215876124758-4dghmea4dv8uf2br7d9st4njg0j5jth7.apps.googleusercontent.com',
    iosBundleId: 'com.chikabooks.chikabooksApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGKfy06xT2j01LoDGIZGKUuWi5M4slNA',
    appId: '1:215876124758:ios:f612d3d0ec4b4793723bf7',
    messagingSenderId: '215876124758',
    projectId: 'chikabooks3rd',
    storageBucket: 'chikabooks3rd.firebasestorage.app',
    iosClientId:
        '215876124758-4dghmea4dv8uf2br7d9st4njg0j5jth7.apps.googleusercontent.com',
    iosBundleId: 'com.chikabooks.chikabooksApp',
  );

}